name: Build and Push Docker Image

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set image tag (by date)
        run: echo "DATE_TAG=$(date +%Y%m%d)" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t qlsomlt/devopsw11-backup:${{ env.DATE_TAG }} .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u qlsomlt --password-stdin

      - name: Push Docker image
        run: docker push qlsomlt/devopsw11-backup:${{ env.DATE_TAG }}
